app/models.py
from . import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime
import time

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index=True)
    email = db.Column(db.String(255),unique=True,index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())    
    password_hash = db.Column(db.String(255))
    pitch_id = db.relationship('Pitch',backref='user',lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'



class Pitch(db.Model):
    __tablename__ = 'pitch'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String)
    name = db.Column(db.String)
    category = db.Column(db.String)
    pitch = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref='pitchez',lazy="dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_pitch(cls):
        Pitch.all_pitch.clear()

    @classmethod
    def get_category(cls,category):
        pitch_cat = Pitch.query.filter_by(category=category).all()
        return pitch_cat

    all_pitch=[]
    def __init__(self,title,name,category,pitch,user):
        self.title=title
        self.name = name
        self.category = category
        self.pitch = pitch
        self.user =user

class Comment(db.Model):

    __tablename__ = 'comments'
    id =db.Column(db.Integer, primary_key=True)
    author = db.Column(db.String)
    body = db.Column(db.String)
    vote = db.Column(db.String)
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitch.id"))

    all_comments = []
    def __init__(self,author,body,vote):
        self.body = body
        self.vote = vote
        self.author = author

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_comment(cls):
        Comment.all_comments.clear()

    @classmethod
    def get_comments(cls):
        comments = Comment.query.all()
        return comments
        # response = []
        # for comment in cls.all_comments:
        #         response.append(comment)

        # return response

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,IntegerField,RadioField,TextAreaField, SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    category = SelectField('Pick Category here',choices=[('inspiration','Inspiration'),
                                                        ('pick-up','Pick Up Lines'),
                                                        ('interview','Interview Pitch'),
                                                        ('product','Product Pitch'),
                                                        ('promotion','Promotion Pitch')], validators=[Required()])
    title = StringField('Pitch Title',validators=[Required()])
    name = StringField('Authors Name', validators=[Required()])
    pitch = TextAreaField('Write your Pitch here', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    author = TextAreaField('Author')
    body = TextAreaField('Write your comment', validators=[Required()])
    vote = RadioField('Vote here',choices=[('upvote','upvote'),
                                            ('downvote','downvote')],validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES

photos = UploadSet('photos',IMAGES)

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)        
    # creating app configurations
    app.config.from_object(config_options[config_name])
    #initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    #registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    #will add the views and forms
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Pitch,User,Comment
from .forms import PitchForm,UpdateProfile,CommentForm
from flask_login import login_required,current_user
from .. import  db,photos

#views
@main.route('/', methods=['GET','POST'])
def index():
    '''
    View root page that returns the index page and its data
    '''
    inspiration=Pitch.query.filter_by(category='inspiration').all()
    interview=Pitch.query.filter_by(category='interview').all()
    pickUp=Pitch.query.filter_by(category='pick-up').all()
    product=Pitch.query.filter_by(category='product').all()
    promotion=Pitch.query.filter_by(category='promotion').all()      
    comments = Comment.query.filter_by(pitch_id=Pitch.id).all()     
    title = 'PITCH-HUB'
    return render_template('index.html',title=title, comments=comments,
                                                     interview = interview,
                                                     inspiration=inspiration,
                                                     pickUp=pickUp,
                                                     product=product,
                                                     promotion=promotion)

@main.route('/create/new', methods = ['GET','POST'])
@login_required
def create():
    '''
    View page that returns a form to create your own pitch
    '''
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        name = form.name.data
        category = form.category.data
        pitch = form.pitch.data
        new_pitch = Pitch(title = title,name=name,category=category,
                          pitch=pitch,user=current_user)
        
        #save pitch method
        new_pitch.save_pitch()
        return redirect(url_for('main.index'))
    title = 'PITCH-HUB'
    return render_template('create.html',title=title,pitch_form=form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = current_user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comment/new',methods=['GET','POST'])
def new_comment():
    form = CommentForm()
    if form.validate_on_submit():
        author = form.author.data
        body = form.body.data
        vote = form.vote.data
        new_comment = Comment(author,body,vote)
        new_comment.save_comment()
        return redirect(url_for('main.index'))
    title = f'Comment'
    return render_template('comment.html',title=title,comment = form)

app/templates/base.html
<link href="https://fonts.googleapis.com/css?family=Encode+Sans+Expanded|Nanum+Myeongjo" rel="stylesheet">
{% extends 'bootstrap/base.html' %}
<!-- style block -->
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!-- Navbar block -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
{% import "macros.html" as macro %}
<div class="container">
        <div class="row">
                {{ wtf.quick_form(comment) }}
            </div>
</div>
{% endblock %}

app/templates/create.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro%}
{% block content %}
    <div class="container">
        {{wtf.quick_form(pitch_form)}}
    </div>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}
{% block content %}
    <h1>WHOOOPS sorry!We cant find that page:(</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
{% block content %}
<div class="container">
        <h3>Want to write a new pitch?Would love to see what you come up with <a href="/create/new">Click Here</a></h3>
</div>
    <div class="container jumbotron">
            <!-- <a href="#trial" class="col-md-4 btn btn-info" data-toggle="collapse">Simple collapsible</a> -->
            <ul class="nav nav-pills nav-justified">
                    <li class="active"><a data-toggle="pill" href="#inspiration">INSPIRATION</a></li>
                    <li><a data-toggle="pill" href="#interview">INTERVIEW</a></li>
                    <li><a data-toggle="pill" href="#pickUp">PICK-UP LINES</a></li>
                    <li><a data-toggle="pill" href="#product">PRODUCT PITCHES</a></li>
                    <li><a data-toggle="pill" href="#promotion">PROMOTION PITCH</a></li>
                  </ul>
                  
                  <div class="tab-content" style="margin:2%;">
                    <div id="inspiration" class="tab-pane fade in active">
                        <div class="row">
                            {{macro.displayPitch(inspiration)}}
                        </div>
                    </div>
                    <div id="interview" class="tab-pane fade">
                        <div class="row">
                            {{macro.displayPitch(interview)}}
                        </div>
                    </div>
                    <div id="pickUp" class="tab-pane fade">
                        <div class="row">
                            {{macro.displayPitch(pickUp)}}
                        </div>
                    </div>
                    <div id="product" class="tab-pane fade">
                            <div class="row">
                                {{macro.displayPitch(product)}}
                            </div>
                    </div>
                    <div id="promotion" class="tab-pane fade">
                            <div class="row">
                                {{macro.displayPitch(promotion)}}
                            </div>
                    </div>
                  </div>
                  <!-- <div class="row">
                        <h1>Comments</h1>
                        <hr>
                        {% if comments %}
                            {{macro.displayComments(comments)}}
                        {% endif %}
                </div> -->
    </div>
{% endblock %}

app/templates/macros.html
<!-- displaying pitch in macros-->
{% macro displayPitch(pitch_list) %}
    {% for pitch in pitch_list %}
    <div class="container col-lg-4">
                <div class="panel panel-info" style="height:auto;width:auto;margin-bottom:20%;margin-left:0%;">
                    <div class="panel-heading">
                        <h2>{{pitch.title}}</h2>
                    </div>
                    <div class="panel-body">
                        <p>{{ pitch.pitch }}</p>
                        <p><i>Written By: </i><b>{{pitch.name}}</b></p>
                        <p><i>Published At: </i><b>{{pitch.posted}}</b></p>
                    </div>
                    <div class="panel-footer">
                        <p>Comment or vote <a href="/comment/new">here</a></p>
                    </div>
                </div>
            </div>
    {% endfor %}
{% endmacro %}

<!-- Displaying comments macro -->
{% macro displayComments(comment_list) %}
    {% for comment in comment_list %}
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 comment-card">
        <p> {{ comment.body}} </p>
        <p> {{ comment.vote}}</p>
        <p><i>{{ comment.author }}</i></p>
    </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">PITCH-HUB</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">HOME</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">LOG OUT</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">LOG IN</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

</div>

app/templates/profile/profile.html
{% extends './base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>
  {% if user == current_user %}
  <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
  {% endif %}
  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
      {% endif %}

  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends './base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %}